databases:
  - name: strengths-app-DB
    databaseName: strengths_app_db_v1fm
    user: strengths_app_db_v1fm_user
    region: singapore

services:
  - type: web
    name: strengths-app-DB
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: render_app
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false